version: '3'
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${USER_NAME}
            MYSQL_PASSWORD: ${USER_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ${MYSQL_DATA}/var/lib/mysql
            - ${MYSQL_ENTRYPOINT}:/docker-entrypoint-initdb.d
        networks: 
            - app-network

    wordpress:
        image: wordpress:5.2.2-php7.2-fpm
        container_name: wordpress
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${USER_NAME}
            WORDPRESS_DB_PASSWORD: ${USER_PASSWORD}
            WORDPRESS_DB_NAME: ${DATABASE_NAME}
        depends_on: 
            - db
        ports:
            - 8080:80
        expose:
            - '9000'
        volumes:
            - ${ROOT}:/var/www/html
        networks: 
            - app-network

    web-server:
        image: nginx:1.13.3
        container_name: web-server
        restart: always
        depends_on: 
            - wordpress
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        volumes:
            - ${ROOT}:/var/www/html
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        links: 
            - wordpress
        networks: 
            - app-network

networks:
    app-network:
        driver: bridge
